### ISSUE TITLE
Front Page Revisions

### ISSUE THREAD

**Issue by jgrimes86** [omgitsmiles/ctrl-your-finances#39]
I think the tag line ('Together, we’re going to make some amazing things!') is meant for Hackonomics, not the Money Magnet theme.  I think it should be removed from the front page.

There should also be less of a gap between the logo and 'Welcome to Money Magnet!'

When a user is logged in, the 'Dashboard' button on the frontpage should look the same as the 'sign up' and 'log in' buttons

**Comment by omgitsmiles** [comment]
Removed padding, rewrote tagline
