### ISSUE TITLE
Navbar Avatar and Styling

### ISSUE THREAD

**Issue by jgrimes86** [omgitsmiles/ctrl-your-finances#40]
The avatar/icon in the navbar should show the first initial of the logged in user.  I think google avatars can be based on a letter input into the icon.

The 'Money Magnet' text needs to be resized to fit the navbar on mobile view.

ALSO: The Navbar dropdown menu and avatar (or maybe even the whole navbar) should not appear on the signup & login pages.

The first (currently blank) dropdown menu should be removed.  This will require respacing the other components on the navbar.

**Comment by omgitsmiles** [comment]
![Image](https://github.com/omgitsmiles/ctrl-your-finances/assets/91231062/ac19f3f2-1a79-438d-b349-46d63877bb86)

Seeing this on mobile view money magnet text fits in the navbar, do you see a different view? uploaded my view.

I don't under that first dropdown menu comment? Only see one dropdown from the avatar with the MenuItems Dashboard, Account, & Logoout.

**Comment by peymere** [comment]
I created conditional rendering of the user avatar/menu based on if a user is logged in. i also changed the avatar to display either the first initials of the user or a profile photo, depending on if there is one (google auth will automatically store a photo url linked to the gmail account)
<img width="430" alt="Screen Shot 2024-03-25 at 1 01 08 PM" src="https://github.com/omgitsmiles/ctrl-your-finances/assets/142445449/29edadda-72f8-45bd-8f0d-7cdcd83a80e4">
<img width="426" alt="Screen Shot 2024-03-25 at 1 01 48 PM" src="https://github.com/omgitsmiles/ctrl-your-finances/assets/142445449/ae76c416-35b0-4bf3-8f52-8d810b83bff7">
<img width="428" alt="Screen Shot 2024-03-25 at 12 50 25 PM" src="https://github.com/omgitsmiles/ctrl-your-finances/assets/142445449/513d16a3-ead1-44cb-8855-e925438571e1">
<img width="427" alt="Screen Shot 2024-03-25 at 12 50 39 PM" src="https://github.com/omgitsmiles/ctrl-your-finances/assets/142445449/26cd77d5-e8b8-42c3-98e6-2ca0ce86fa8d">

**Comment by peymere** [comment]
there are all the use cases for avatar display names
